[package]
name = "oasis-cli"
version = "0.1.0"
description = "Oasis developer tools"
authors = ["Oasis Labs <feedback@oasislabs.com>"]
edition = "2018"

[dependencies]
cargo_toml = "0.6"
chrono = "0.4"
clap = "2.33"
colored = "1.8"
dirs = "2.0.1"
failure = "0.1"
mantle-rpc = { version = "0.1", features = ["import"] }
rand = "0.7"
regex = "1.1"
serde = { version = "1.0", features = ["derive"] }
walrus = "0.8"
