#!/bin/bash

set -e

export OASIS_TEST_BASE=/tmp/oasis-cli.$RANDOM
export OASIS_CLI_BINARY=$(pwd)/target/debug/oasis

# Just use the HOME directory as the base directory
# for configuration and data generated by the CLI.
export XDG_CONFIG_HOME=
export XDG_DATA_HOME=

# Use user's existing Rust install.
export CARGO_HOME=$HOME/.cargo
export RUSTUP_HOME=$HOME/.rustup

# Mock home dir
export HOME=$OASIS_TEST_BASE

# Set expected directory paths as env vars (not used by CLI).
# The CLI is expected to conform to XDG on Linux and the equivalent on macOS.
if [ $(uname) == "Darwin" ]; then
    export OASIS_CONFIG_DIR=$HOME/Library/Preferences
    export OASIS_DATA_DIR=$HOME/Library/"Application Support"
elif [ $(uname) == "Linux" ]; then
    export OASIS_CONFIG_DIR=$OASIS_TEST_BASE/.config
    export OASIS_DATA_DIR=$OASIS_TEST_BASE/.local/share
fi

mkdir -p $OASIS_TEST_BASE

if [ ! -f $OASIS_CLI_BINARY ]; then
    cargo build
fi

source tests/tests.sh
test_all

# Clean up files when tests pass.
rm -r $OASIS_TEST_BASE
