version: 2.1


executors:
  rust:
    environment:
      PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
    docker:
      - image: oasislabs/rust:latest
    resource_class: xlarge


jobs:
  test:
    executor: rust
    steps:
      - checkout
      - run: cargo fmt -- --check
      - run:
          name: Python checkstyle
          working_directory: tests
          command: |
            yapf --diff *.py
            pylint *.py
      - run: cargo build
      - run: cargo test
      - run:
          name: Install oasis-build
          command: |
            target/debug/oasis set-toolchain latest
            mv ~/.local/bin/oasis-build ~/.cargo/bin
            rm ~/.local/bin/oasis
      - run: pytest -n 8 tests/

  clippy:
    executor: rust
    steps:
      - checkout
      - run:
          name: Clippy
          command: |
            rustup component add clippy || exit 0
            cargo clippy --all-features -- -D clippy::all


workflows:
  version: 2

  pull_request:
    jobs:
      - test
      - clippy
