use std::io::{self, Write as _};

pub fn confirm(question: &str, default: bool) -> Result<bool, failure::Error> {
    print!("{} ", question);
    let mut s = String::new();
    let _ = io::stdout().flush();
    let _ = io::stdin().read_line(&mut s)?;
    let s = s.trim_end().to_string();

    let r = match &*s.to_lowercase() {
        "y" | "yes" => true,
        "n" | "no" => false,
        "" => default,
        _ => false,
    };

    println!();

    Ok(r)
}

pub fn ask_string(question: &str) -> Result<String, failure::Error> {
    let mut s = String::new();

    println!("{}", question);
    let _ = io::stdin().read_line(&mut s)?;
    Ok(s.trim_end().to_string())
}

pub fn introduction() {
    println!("Welcome to Oasis Development Environment! My name is Oli and I can help you set things up.");
    println!("We will set up the configuration options that you will use");
    println!();
    println!("We hope to collect telemetry data from the logging generated by user commands. This telemetry data");
    println!("will give us insights on what problems users encounter and be able to improve the software more quickly.");
}
